services:
    nextjs:
        build: .
        container_name: desa-nextjs
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NODE_ENV=production
